include_guard(GLOBAL)

set(FALCON_BEDROCK_DATA_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(FALCON_BEDROCK_DATA_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(FALCON_BEDROCK_DATA_MANIFEST "${FALCON_BEDROCK_DATA_ROOT}/versions.json")

file(READ "${FALCON_BEDROCK_DATA_MANIFEST}" FALCON_BEDROCK_DATA_MANIFEST_CONTENT)
string(JSON FALCON_BEDROCK_DATA_LATEST_PROTOCOL GET "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" latest)

if(NOT FALCON_BEDROCK_DATA_PROTOCOL)
    set(FALCON_BEDROCK_DATA_PROTOCOL "${FALCON_BEDROCK_DATA_LATEST_PROTOCOL}")
endif()

function(falcon_bedrock_data_find_version protocol outIndex)
    string(JSON versionCount LENGTH "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions)
    set(found -1)
    if(versionCount GREATER 0)
        math(EXPR lastVersion "${versionCount} - 1")
        foreach(index RANGE ${lastVersion})
            string(JSON candidate GET "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions ${index} protocol)
            if(candidate EQUAL protocol)
                set(found ${index})
            endif()
        endforeach()
    endif()
    if(found EQUAL -1)
        message(FATAL_ERROR "Falcon-BedrockData has no data for protocol ${protocol}")
    endif()
    set(${outIndex} ${found} PARENT_SCOPE)
endfunction()

function(falcon_bedrock_data_minecraft_version outVar)
    falcon_bedrock_data_find_version(${FALCON_BEDROCK_DATA_PROTOCOL} versionIndex)
    string(JSON minecraftVersion GET "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions ${versionIndex} minecraftVersion)
    set(${outVar} "${minecraftVersion}" PARENT_SCOPE)
endfunction()

function(falcon_bedrock_data_directory outVar)
    falcon_bedrock_data_find_version(${FALCON_BEDROCK_DATA_PROTOCOL} versionIndex)
    set(${outVar} "${FALCON_BEDROCK_DATA_ROOT}/data/${FALCON_BEDROCK_DATA_PROTOCOL}" PARENT_SCOPE)
endfunction()

function(falcon_bedrock_data_file name outVar)
    falcon_bedrock_data_find_version(${FALCON_BEDROCK_DATA_PROTOCOL} versionIndex)
    string(JSON fileCount LENGTH "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions ${versionIndex} files)
    set(expectedHash "")
    if(fileCount GREATER 0)
        math(EXPR lastFile "${fileCount} - 1")
        foreach(index RANGE ${lastFile})
            string(JSON candidate GET "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions ${versionIndex} files ${index} name)
            if(candidate STREQUAL name)
                string(JSON expectedHash GET "${FALCON_BEDROCK_DATA_MANIFEST_CONTENT}" versions ${versionIndex} files ${index} sha256)
            endif()
        endforeach()
    endif()
    if(expectedHash STREQUAL "")
        message(FATAL_ERROR "Falcon-BedrockData protocol ${FALCON_BEDROCK_DATA_PROTOCOL} does not provide ${name}")
    endif()

    set(path "${FALCON_BEDROCK_DATA_ROOT}/data/${FALCON_BEDROCK_DATA_PROTOCOL}/${name}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Falcon-BedrockData file is missing: ${path}")
    endif()

    file(SHA256 "${path}" actualHash)
    if(NOT actualHash STREQUAL expectedHash)
        message(FATAL_ERROR "Falcon-BedrockData checksum mismatch for ${path}")
    endif()

    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}" "${FALCON_BEDROCK_DATA_MANIFEST}")
    set(${outVar} "${path}" PARENT_SCOPE)
endfunction()

function(falcon_bedrock_data_embed_binary)
    cmake_parse_arguments(ARG "" "FILE;NAMESPACE;SYMBOL;OUTPUT" "" ${ARGN})
    falcon_bedrock_data_file("${ARG_FILE}" sourcePath)

    file(READ "${sourcePath}" hexContent HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," FALCON_BEDROCK_DATA_BYTES "${hexContent}")
    string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n"
            FALCON_BEDROCK_DATA_BYTES "${FALCON_BEDROCK_DATA_BYTES}")

    set(FALCON_BEDROCK_DATA_NAMESPACE "${ARG_NAMESPACE}")
    set(FALCON_BEDROCK_DATA_SYMBOL "${ARG_SYMBOL}")
    configure_file("${FALCON_BEDROCK_DATA_CMAKE_DIR}/EmbeddedBinary.h.in" "${ARG_OUTPUT}" @ONLY)
endfunction()

function(falcon_bedrock_data_embed_text)
    cmake_parse_arguments(ARG "" "FILE;NAMESPACE;SYMBOL;DELIMITER;OUTPUT" "" ${ARGN})
    falcon_bedrock_data_file("${ARG_FILE}" sourcePath)

    file(READ "${sourcePath}" FALCON_BEDROCK_DATA_TEXT)

    set(FALCON_BEDROCK_DATA_NAMESPACE "${ARG_NAMESPACE}")
    set(FALCON_BEDROCK_DATA_SYMBOL "${ARG_SYMBOL}")
    set(FALCON_BEDROCK_DATA_DELIMITER "${ARG_DELIMITER}")
    configure_file("${FALCON_BEDROCK_DATA_CMAKE_DIR}/EmbeddedText.h.in" "${ARG_OUTPUT}" @ONLY)
endfunction()
